In [5]:
num_of_country = int(input())

names = set()
for i in range(1,num_of_country+1):
    store_name = input()
    names.add(store_name)

names


{'q', 'w'}

In [6]:
len(names)

2

In [9]:
a = 'w'

names.remove(a)

In [ ]:
9
1 2 3 4 5 6 7 8 9
10
pop
remove 9
discard 9
discard 8
remove 7
pop 
discard 6
remove 5
pop 
discard 5

{'q'}

In [24]:
s = {1,2}
sum(s)

3

In [26]:
n = int(input())
s = set(map(int, input().split()))

N = int(input())

for i in range(1,N+1):
    b = list(map(str, input().split()))
    
    
    if len(b) == 1 and b == "pop":
        s.pop()
    elif b[0] == "remove":
        s.remove(int(b[1]))
    elif b[0] == "discard":
        s.discard(int(b[1]))

sum(s)

3

In [ ]:
1 2 3 6 5 4 4 2 5 3 6 1 6 5 3 2 4 1 2 5 1 4 3 6 8 4 3 1 5 6 2 

In [56]:
a_ = int(input())
a = list(map(int, input().split()))

frequencies = {}

for num in a:
    frequencies[num] = frequencies.get(num, 0) + 1

for key, value in frequencies.items():
    if value == 1:
        print(key)

8


In [54]:
a = list(map(int,input().split()))
#data = [1, 2, 2, 3, 3, 3]
frequencies = {x: a.count(x) for x in set(a)}
frequencies
for key,value in frequencies.items():
    if value == 1:
        print(key)

8


In [ ]:
a = set(map(int,input().split()))
print(a)
b = int(input())
print(b)
count = 0
for i in range(1,b+1):
    
    c = set(map(int,input().split()))
    print(a.issuperset(c))
    if a.issuperset(c) is True:
        count += 1
        
if count == b:
    print(True)
else:
    print(False)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 45, 78, 84, 23}
2
True
False
False


In [42]:
s = set("Hacker")
print(s)
print(s.union("Rank"))
print(s)
#set(['a', 'R', 'c', 'r', 'e', 'H', 'k', 'n'])

print(s.union(set(['R', 'a', 'n', 'k'])))
#set(['a', 'R', 'c', 'r', 'e', 'H', 'k', 'n'])

{'r', 'H', 'e', 'k', 'c', 'a'}
{'n', 'e', 'k', 'c', 'a', 'R', 'r', 'H'}
{'r', 'H', 'e', 'k', 'c', 'a'}
{'R', 'r', 'H', 'n', 'e', 'k', 'c', 'a'}


In [ ]:
m = int(input())
a = set(map(int,input().split()))
n = int(input())
b = set(map(int,input().split()))


c = a.symmetric_difference(b)
c = sorted(c)
for i in c:
    print(i)

5
9
11
12


In [34]:
a = {2, 4, 5, 9, 89}
b = {2, 4, 5, 9, 99}
c = b.symmetric_difference(a)
for i in c:
    print(i)

89
99


In [3]:
n = int(input().strip())
if n % 2 != 0:
    print('Weird')
elif n % 2 == 0 and n in range(2,5):
    print('Not Weird')

Not Weird


In [27]:
import numpy

n, m = map(int, input().split())   
print(n,m)
matrix = []

for _ in range(n):
    row = list(map(int, input().split()))
    print(row)
    matrix.append(row)
print(matrix)
arr = numpy.array(matrix)
print(arr.transpose())
print(arr.flatten())

2 2
[1, 2]
[3, 4]
[[1, 2], [3, 4]]
[[1 3]
 [2 4]]
[1 2 3 4]


In [23]:
import numpy
num_list = list(map(int, input("Enter numbers: ").split()))
#n = '2 5 6 3 58  4 2 5 6'
#num_list = list(map(int, n.split()))
my_array = numpy.array(num_list)
print(my_array.reshape(3,3))



[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
n = 6
for i in range(1,n+1):
    print(i,end="")

123456

In [ ]:
def is_leap(year):
    leap = False
    
    while (year % 400 == 0) or (year % 4 == 0 and year % 100 != 0):
        return True
        
        
    return leap
    
    

year = int(input())
print(is_leap(year))

False


In [3]:
with open(r'G:\campusx ML algo code\File Handling\example.txt','r') as file:
    content = file.read()
    print(content)

Starting with full happiness, Joy and Positive Energy.
There are few things that we should ignore while moving ahead, 
which is actually distraction/Obstacles that takes our attention and focus 
and its assigned task is to shift our Energy to somewhere else.


In [5]:
with open(r'G:\campusx ML algo code\File Handling\example.txt','r') as file:
    for l in file:
        print(l.strip())

Starting with full happiness, Joy and Positive Energy.
There are few things that we should ignore while moving ahead,
which is actually distraction/Obstacles that takes our attention and focus
and its assigned task is to shift our Energy to somewhere else.


In [7]:
#append file operation

with open(r'G:\campusx ML algo code\File Handling\example.txt','a') as file:
    file.write('Write your thoughts below\n')
    file.write('Kindly don\'t forget to subscribe us. \n')


In [8]:
lines = ['First Line\n','Second Line\n','Third Line\n']
with open(r'G:\campusx ML algo code\File Handling\example.txt','a') as file:
    file.writelines(lines)

In [11]:
with open(r'G:\campusx ML algo code\File Handling\example.txt','r') as source_file:
    content = source_file.read()

with open('destination.txt','w') as destination_file:
    destination_file.write(content)

In [ ]:
### Reading the Files 

In [38]:
file = open(r'G:\campusx ML algo code\destination.txt','r')
content = file.read()
print(content)

Starting with full happiness, Joy and Positive Energy.
There are few things that we should ignore while moving ahead, 
which is actually distraction/Obstacles that takes our attention and focus 
and its assigned task is to shift our Energy to somewhere else.Write your thoughts below
Write your thoughts below
Kindly don't forget to subscribe us. 
First Line
Second Line
Third Line



In [58]:
file = open(r'G:\campusx ML algo code\destination.txt','r')
content = list(file)
print(content)

['Starting with full happiness, Joy and Positive Energy.\n', 'There are few things that we should ignore while moving ahead, \n', 'which is actually distraction/Obstacles that takes our attention and focus \n', 'and its assigned task is to shift our Energy to somewhere else.Write your thoughts below\n', 'Write your thoughts below\n', "Kindly don't forget to subscribe us. \n", 'First Line\n', 'Second Line\n', 'Third Line\n', 'Fourth LineFifth LineSixth Line\n', '7th Line\n']


In [40]:
file = open(r'G:\campusx ML algo code\destination.txt','r')
for line in file:
    print(line.strip())

Starting with full happiness, Joy and Positive Energy.
There are few things that we should ignore while moving ahead,
which is actually distraction/Obstacles that takes our attention and focus
and its assigned task is to shift our Energy to somewhere else.Write your thoughts below
Write your thoughts below
Kindly don't forget to subscribe us.
First Line
Second Line
Third Line


In [69]:
with open(r'G:\campusx ML algo code\destination.txt','r') as file:
    data = file.read()
    print(data)
    print(len(data))
    file.seek(2)
    print(file.read())
    print(file.tell())

Starting with full happiness, Joy and Positive Energy.
There are few things that we should ignore while moving ahead, 
which is actually distraction/Obstacles that takes our attention and focus 
and its assigned task is to shift our Energy to somewhere else.Write your thoughts below
Write your thoughts below
Kindly don't forget to subscribe us. 
First Line
Second Line
Third Line
Fourth LineFifth LineSixth Line
7th Line

423
arting with full happiness, Joy and Positive Energy.
There are few things that we should ignore while moving ahead, 
which is actually distraction/Obstacles that takes our attention and focus 
and its assigned task is to shift our Energy to somewhere else.Write your thoughts below
Write your thoughts below
Kindly don't forget to subscribe us. 
First Line
Second Line
Third Line
Fourth LineFifth LineSixth Line
7th Line

434


In [84]:
with open(r'G:\campusx ML algo code\destination.txt','r') as file:
    data = file.read()
    #print(data)

with open(r'G:\campusx ML algo code\copy.txt','w') as file:
    data1 = file.write(data)
    #print(data1)

with open(r'G:\campusx ML algo code\copy.txt','r') as file:
    #file.seek(0)
    data1 = file.read()
    print(data1)

Starting with full happiness, Joy and Positive Energy.
There are few things that we should ignore while moving ahead, 
which is actually distraction/Obstacles that takes our attention and focus 
and its assigned task is to shift our Energy to somewhere else.Write your thoughts below
Write your thoughts below
Kindly don't forget to subscribe us. 
First Line
Second Line
Third Line
Fourth LineFifth LineSixth Line
7th Line



In [78]:
import os
os.rename('copy.txt','cut.txt')

In [79]:
import os
os.remove('cut.txt')

In [5]:
from mypackage.module2 import multiply

multiply(9,6)

54


In [6]:
try:
    from mypackage.module1 import addition
    addition(9,6)
except ImportError:
    print('Module Not Found')



15


In [ ]:
# Solid Principles

## Single Responsibility Program

In [ ]:
class UserRegister:
    def registration(self,uname,pwd,email):
        print("{0} has been successfully registered".format(uname))

    def logerror(self, error):
        print('Error Log')

In [15]:
class Fraction:
    
    def __init__(self,n1,d1,n2,d2):
        self.n1 = n1
        self.d1 = d1
        self.n2 = n2
        self.d2 = d2

    def add(self):
        a1 = (self.n1*self.d2+self.n2*self.d1)
        print(a1)
        a2 = (self.d1*self.d2)
        print(a2)
        addition = f'{a1}/{a2}'
        print(addition)

    def sub(self):
        subtraction = (self.n1*self.d2-self.n2*self.d1)/(self.d1*self.d2)
        print(addition)

    def mult(self):
        multiplication = (self.n1*self.n2)/(self.d1*self.d2)
        print(multiplication)

    def div(self):
        division = (self.n1*self.n2)/(self.d1*self.d2)
        print(division)



In [16]:
obj1 = Fraction(2,3,4,5)

In [17]:
obj1.add()

22
15
22/15


In [ ]:
try : 
    print('Hello Wrold')
except:
    print('Caught Error')