In [8]:
# creating Numpy Array

import numpy as np

arr1 = np.array([1,2,3,4])
type(arr1)

numpy.ndarray

In [16]:
r1_10 = [i for i in range(1,11)]
arr2 = np.array(r1_10)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr3 = np.array([[1,2,4,5],[34,5,4,3],[56,4,3,4]])
arr3.size

12

In [34]:
r1_10 = [i for i in range(1,21) if i % 2==0]
arr4 = np.array(r1_10)
arr4

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [35]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


## Practice Questions
Create a 3D array and print its dimensions.
Find the shape and size of a 4×4 matrix.
Print the datatype of an integer array.

In [38]:
arr5 = np.array([[[1,2]]])
arr5.ndim

3

In [43]:
arr6 = np.array([[9,8,7,6],[5,4,3,2],[5,4,3,2],[5,4,3,2]])
arr6.shape
arr6.size
arr6.dtype

dtype('int64')

In [57]:
a1 = np.ones((3, 2))
a1

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [52]:
arr5 = np.array([[],[],[]])
arr5.shape

(3, 0)

In [59]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [66]:
a = np.arange(10, 51)
a.ndim

1

In [63]:
np.linspace(1, 10, 6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [72]:
arr = np.arange(3, 15)

new_arr = arr.reshape(3, 4)
print(new_arr)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [76]:
flt = new_arr.flatten()
flt.shape

(12,)

### Practice Questions
Create an array from 1 to 16 and reshape to (4, 4).
Convert a 2D array into 1D.
Reshape an array into 3 dimensions.

In [79]:
p1 = np.arange(1,17)
p2 = p1.reshape(4,4)

In [83]:
p3 = p2.flatten()
p3.ndim

1

In [92]:
p3.reshape(2,2,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [96]:
p1[0]

np.int64(1)

In [119]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr2[-1:])

[[4 5 6]]


### Practice Questions
    Print the middle element of an array.
    Extract the first row from a 2D array.
    Extract the last column from a matrix.
    Slice elements from index 2 to 6.

In [124]:
p6 = np.arange(1,11)
p6[int(len(p6)/2)]


np.int64(6)

In [132]:
p6a = p6.reshape(2,5)
p6a[0,2:5]

array([3, 4, 5])

    Add 10 to every element.
    Multiply all elements by 5.
    Square all elements of an array.
    Add two arrays together.

In [ ]:
p7 = np.array([1,2,3,4,5,6])
p7a = np.array([6,7,8,9,10,11])
print(p7 + 10)
print(p7 * 5)
print(p7 ** 2)
print(p7 + p7a)

[11 12 13 14 15 16]
[ 5 10 15 20 25 30]
[ 1  4  9 16 25 36]
[ 7  9 11 13 15 17]


    Find the mean of an array.
    Find variance and standard deviation.
    Find maximum and minimum values.
    Compute row-wise sum of a matrix.
    Compute column-wise mean.

In [148]:
print(f"Mean : {p7.mean()}, Variance : {round(p7.var(),3)}, Standard Deviation : {round(p7.std(),3)}, Maximum : {p7.max()}, Minimum : {p7.min()}")
p7b = p7.reshape(2,3)
print(p7b)
print(p7b.mean(axis=0))

Mean : 3.5, Variance : 2.917, Standard Deviation : 1.708, Maximum : 6, Minimum : 1
[[1 2 3]
 [4 5 6]]
[2.5 3.5 4.5]


In [ ]:
np.random.rand(3, 3)   # uniform[0,1]

array([[0.24758193, 0.41959019, 0.00146695],
       [0.41254859, 0.54572437, 0.39185154],
       [0.29503104, 0.00853556, 0.1989088 ]])

In [165]:
np.random.randint(1,10,size=(4,4))

array([[6, 6, 6, 7],
       [9, 1, 1, 1],
       [7, 6, 5, 7],
       [3, 9, 8, 3]], dtype=int32)

In [166]:
np.random.randint(50,100)

58

In [213]:
np.random.choice(['a','b','c'],4)

array(['c', 'a', 'a', 'a'], dtype='<U1')

In [255]:
np.random.seed(42)
a = [np.random.randint(1,10) for _ in range(1,11)]
a


[7, 4, 8, 5, 7, 3, 7, 8, 5, 4]

In [245]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

b = np.array([10, 20, 30])

print(np.multiply(arr,b))

[[ 10  40  90]
 [ 40 100 180]]


    Multiply each column by different values.
    Create two compatible arrays and apply broadcasting.

In [250]:
b[b != 20]

array([10, 30])

    Extract all even numbers.
    Extract values greater than 10.
    Replace negative values with 0.
    Count values greater than mean.

In [266]:
a = [np.random.randn() for _ in range(1,11)]
print(a)
a = np.array(a)
print(type(a))
print(a[a < 0])


[1.1302281938970369, 0.37311891472941866, -0.3864729505645555, -1.1587702419250825, 0.5661128267810409, -0.7044534503765905, -1.3779393038224825, -0.35311665200706827, -0.46146571817418325, 0.06665727850862435]
<class 'numpy.ndarray'>
[-0.38647295 -1.15877024 -0.70445345 -1.3779393  -0.35311665 -0.46146572]


In [278]:
b = np.array([-2,-5,1, 2, 3, 4, 5, 6, 7, 8, 9, 10])  # np.random.randint(1,11)
print(type(b))
b[b % 2 == 0]

<class 'numpy.ndarray'>


array([-2,  2,  4,  6,  8, 10])

In [279]:
b[b<0] = 0
b

array([ 0,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [292]:
import numpy.ma as ma

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

mask = np.eye(3, dtype=int)

marr = ma.masked_array(arr, mask)
print(marr)

[[-- 2 3]
 [4 -- 6]
 [7 8 --]]


    Mask diagonal elements.
    Mask values greater than 10.
    Replace masked values with mean.
    Compute sum of unmasked values.

In [306]:
p12 = np.array([[1,12],[22,24]])
p12
mask_ = p12[p12 > 10]
m = ma.masked_array(p12,p12 > 10)
print(m)

[[1 --]
 [-- --]]


In [309]:
mean_rep = mask_.mean()

In [310]:
m.filled(mean_rep)

array([[ 1, 19],
       [19, 19]])

In [311]:
m.sum()

np.int64(1)

    Find index of largest element.

In [327]:
p12 = np.array([1,2,33,11])
np.where(p12==p12.max())

(array([2]),)

    Sort each row of a matrix.

In [331]:
arr = np.array([
    [1, 12, 3],
    [4, 15, 6],
    [7, 28, 9]
])

np.sort(arr)


array([[ 1,  3, 12],
       [ 4,  6, 15],
       [ 7,  9, 28]])

    Multiply two matrices.
    Find transpose of a matrix.
    Find determinant of a matrix.
    Compute inverse of a matrix.

In [332]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print(np.dot(A, B))

[[19 22]
 [43 50]]


In [334]:
np.multiply(A,B)

array([[ 5, 12],
       [21, 32]])

In [336]:
B.T

array([[5, 7],
       [6, 8]])

In [338]:
np.linalg.det(B)

np.float64(-2.000000000000005)

In [339]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [342]:
dtype = [('name', 'U10'), ('age', 'i4')]

arr = np.array([
    ('Alice', 25),
    ('Bob', 30)
], dtype=dtype)

print(arr)

[('Alice', 25) ('Bob', 30)]


In [343]:
x = np.array([1, 2])
y = np.array([3, 4])

print(np.vstack((x, y)))
print(np.hstack((x, y)))

[[1 2]
 [3 4]]
[1 2 3 4]


In [344]:
arr = np.arange(1, 9)
print(np.split(arr, 4))

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [352]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

#np.hstack((A,B))

np.split(A,2)

[array([[1, 2]]), array([[3, 4]])]

In [355]:
np.concatenate((A,B),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### The NumPy Mega Project: "The Neural Satellite Image Processor"
In this project, you will act as a scientist processing satellite imagery. You won't use Pandas at all. Instead, you'll treat images as 3D NumPy arrays (Height, Width, Color Channels) and apply linear algebra and statistical filters.

Phase 1: Creating the "Universe" (Array Creation)The Task: Generate a 1000 x 1000 x 3 array of random integers (0-255) to represent a raw RGB satellite image.

In [1]:
import numpy as np

# 1. Generate a random 1000x1000 RGB image (0-255)
image = np.random.randint(0, 256, (1000, 1000, 3), dtype='uint8')

In [6]:
image[400:600,400:600,0] = 255

In [7]:
print(f"Image Shape: {image.shape}")
print(f"Memory size: {image.nbytes / 1e6:.2f} MB")

Image Shape: (1000, 1000, 3)
Memory size: 3.00 MB
